---

- name: aws configuration | process
  set_fact:
    result: >-
      {{ path | process_aws_credentials(profile, access_key, secret_key) }}

- name: output variables | set
  set_fact:
    aws_access_key_id: "{{ result.key_id }}"
    aws_secret_key: "{{ result.key }}"
