
 - name: "process input arguments"
   set_fact:
       node_name: "{{ node_name|default('') }}"
       node_range: "{{ node_range|default(0)|int }}"
       node_list: "{{ node_list|default([]) }}"

 - name: "ensure temporary file directory"
   file:
       name: "{{ work_dir }}/tmp"
       state: directory
       mode: 0755

 - name: "create temporary file for startup script"
   shell: mktemp --tmpdir={{ work_dir }}/tmp
   register: mktemp

 - name: "generate startup script"
   template:
       src: startup.j2
       dest: "{{ mktemp.stdout }}"
       mode: 0755

 - name: "bring up nodes"
   shell: "{{ mktemp.stdout }}"
   args:
       chdir: "{{ work_dir }}"

 - name: "clean up temporary file"
   file:
       name: "{{ mktemp.stdout }}"
       state: absent

 - name: "clear role facts"
   set_fact:
       node_name: ""
       node_range: 0
       node_list: []

