---

  - name: mesos | service | logic flags | compute
    set_fact:
        remove_data_root: "{{ state == 'absent' }}"
        remove_install_root: "{{ state == 'absent' }}"
        stop_mesos_services: "{{ state == 'absent' }}"
        do_install: >
            {{ state == "present" or state == "stopped" or
               state == "started" or state == "restarted" or
               state == "reloaded" }}
        notify_services: >
            {{ state == "stopped" or state == "started"
            or state == "restarted" or state == "reloaded" }}


  - name: mesos | quorum | url | compute
    set_fact:
        mesos_zookeeper_url: >
            {{ groups[zookeeper_ansible_group] |
                zk_url(hostvars, zookeeper_net_interface, zookeeper_client_port)
                }}/mesos/{{ mesos_cluster_name }}

  - name: mesos | quorum | count | compute
    set_fact:
        mesos_quorum: >
            {{ (groups[zookeeper_ansible_group]|length)//2 + 1 }}
    when: mesos_quorum == 0

  - name: mesos | prefix | record
    set_fact:
        mesos_prefix: "{{ mesos_install_root }}/\
                           mesos-{{ mesos_version }}"

  - name: mesos | build | probe
    stat:
        path: "{{ mesos_prefix }}/build"
    when: do_install|bool
    register: build_probe

  - name: mesos | build | flag | compute
    set_fact:
        do_compile: >
            {{ (do_install|bool) and
                (not (build_probe.stat.exists|bool) or (recompile|bool)) }}

