---
    instances: {}
    name: default
    options:
        ansible_groups_amend: true
        ansible_groups_amend_mode: ip
    placement_groups: {}
    security_groups: {}
    ssh_keys: {}
    state: running
    templates: {}

