---

  - name: service | group | create
    group:
        name: "{{ group }}"
        state: present
        system: yes

  - name: service | user | create
    user:
        group: "{{ group }}"
        name: "{{ user }}"
        state: present
        system: yes

  - name: service | conf | generate
    template:
        src: service.conf.j2
        dest: /etc/init/{{ name|mandatory }}.conf
        backup: yes
        mode: 0644

