---

- name: initialize
  script: >-
    girder-post-install.py
      --user {{ girder_admin_user }}
      --password {{ girder_admin_password }}
      --host {{ hostvars[inventory_hostname]
                        ['ansible_' + girder_net_interface]
                        ['ipv4']
                        ['address'] }}
      --port {{ girder_port }}
      --data-root {{ girder_data_root }}
      --broker {{ romanesco_celery_broker }}
      --hdfs-user {{ hdfs_user }}
      --hdfs-namenode {{ hostvars[groups[hdfs_namenode_ansible_group][0]]
                                 ["ansible_" + hdfs_net_interface]
                                 ["ipv4"]
                                 ["address"] }}
      --hdfs-port 8020
      --web-hdfs-port 50080
  when: do_initialization|bool

- name: initialize | mark
  file:
    path: "{{ girder_data_root }}/.initialized"
    state: touch
  when: do_initialization|bool
