---

  - name: hadoop | service | hdfs | logic flags | compute
    set_fact:
        remove_data_root: "{{ state == 'absent' }}"
        remove_install_root: "{{ state == 'absent' }}"
        stop_hdfs_services: >
            {{ (state == 'absent' or (format|bool)) and
               inventory_hostname in groups.get(hdfs_namenode_group, []) }}
        do_install: >
            {{state == "present" or state == "stopped" or
              state == "started" or state == "restarted" or
              state == "reloaded"}}
        notify_services: >
            {{state == "stopped" or state == "started" or
              state == "restarted" or state == "reloaded"}}
        notify_format: >
            {{state == "present" or state == "started" or
              state == "restarted" or state == "reloaded"}}

  - name: hadoop | deps | install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - apt-utils
      - openjdk-7-jre-headless
      - openssh-client
      - openssh-server
      - rsync
      - sudo
      - tar
      - gzip
      - wget
    when: do_install|bool

  - name: hadoop | service | hdfs | datanode | stop
    service:
        name: hdfs-datanode
        state: stopped
    ignore_errors: true
    when: stop_hdfs_services|bool

  - name: hadoop | service | hdfs | namenode | stop
    service:
        name: hdfs-namenode
        state: stopped
    when: stop_hdfs_services|bool

  - name: hadoop | install root | delete
    file:
        path: "{{ hadoop_install_root }}"
        state: absent
    when: remove_install_root|bool

  - name: hadoop | install root | create
    file:
        path: "{{ hadoop_install_root }}"
        state: directory
    when: do_install|bool

  - name: hadoop | pkg | download
    get_url:
        url: "http://archive.apache.org/dist/hadoop/core/\
              hadoop-{{ hadoop_version }}/\
              hadoop-{{ hadoop_version }}.tar.gz"
        dest: "{{ hadoop_install_root }}/hadoop-{{ hadoop_version }}.tar.gz"
        force: no
    when: do_install|bool

  - name: hadoop | pkg | unpack
    unarchive:
        copy: no
        creates: "{{ hadoop_install_root }}/hadoop-{{ hadoop_version }}"
        dest: "{{ hadoop_install_root }}"
        mode: 0776
        src: "{{ hadoop_install_root }}/hadoop-{{ hadoop_version }}.tar.gz"
    when: do_install|bool

  - name: hadoop | prefix | record
    set_fact:
        hadoop_prefix: "{{ hadoop_install_root }}/hadoop-{{ hadoop_version }}"
    when: do_install|bool

  - name: hadoop | conf | record
    set_fact: hadoop_conf={{ hadoop_prefix }}/etc/hadoop
    when: do_install|bool

  - name: hadoop | log | perms | set
    file:
        path: "{{ hadoop_prefix }}/logs"
        mode: 0750
        state: directory
    when: do_install|bool

