---

- name: hadoop | deps | install
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apt-utils
    - openjdk-7-jre-headless
    - openssh-client
    - openssh-server
    - rsync
    - sudo
    - tar
    - gzip
    - wget
  when: do_install|bool

- name: hadoop | service | hdfs | datanode | stop
  service:
    name: hdfs-datanode
    state: stopped
  ignore_errors: true
  when: stop_services|bool

- name: hadoop | service | hdfs | namenode | stop
  service:
    name: hdfs-namenode
    state: stopped
  ignore_errors: true
  when: stop_services|bool

- name: hadoop | install root | delete
  file:
    path: "{{ hadoop_install_root }}"
    state: absent
  when: remove_install_root|bool

- name: hadoop | install parent | create
  file:
    path: "{{ hadoop_install_parent }}"
    state: directory
  when: do_install|bool

- name: hadoop | data root | create
  file:
    path: "{{ hadoop_data_root }}"
    state: directory
    mode: 0755
  when: do_install|bool

- name: hadoop | data root | owner | set
  file:
    path: "{{ hadoop_data_root }}"
    state: directory
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: 0775
  when: do_install|bool

- name: hadoop | pkg | download
  get_url:
    url: "http://archive.apache.org/dist/hadoop/core/\
          hadoop-{{ hadoop_version }}/\
          hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_install_parent }}/hadoop-{{ hadoop_version }}.tar.gz"
    force: no
  when: create_install_root|bool

- name: hadoop | pkg | unpack
  unarchive:
    copy: no
    creates: "{{ hadoop_install_parent }}/hadoop-{{ hadoop_version }}"
    dest: "{{ hadoop_install_parent }}"
    mode: 0776
    src: "{{ hadoop_install_parent }}/hadoop-{{ hadoop_version }}.tar.gz"
  when: create_install_root|bool

- name: hadoop | pkg | unpack | rename
  shell: >-
    mv
    "{{ hadoop_install_parent }}/hadoop-{{ hadoop_version }}"
    "{{ hadoop_install_root }}"
  when: create_install_root|bool
  changed_when: >-
    (hadoop_install_parent + "/hadoop-" + hadoop_version) !=
    hadoop_install_root

- name: hadoop | log | perms | set
  file:
    path: "{{ hadoop_install_root }}/logs"
    mode: 0755
    state: directory
  when: do_install|bool
