---

  - name: "[HADOOP][HDFS][FS] format"
    become_user: "{{ hdfs_user }}"
    shell: "{{ hadoop_prefix }}/bin/hdfs namenode \
                -format -nonInteractive || true"
    when: not (format|bool) and state != "stopped"
    register: format_result
    failed_when: "'Error' in format_result.stderr"

  - name: "[HADOOP][HDFS][FS] format (force)"
    become_user: "{{ hdfs_user }}"
    shell: "{{ hadoop_prefix }}/bin/hdfs namenode -format -force"
    when: (format|bool) and state != "stopped"
    register: format_result
    failed_when: "'Error' in format_result.stderr"

  - name: "[HADOOP][HDFS][SERVICE][NAME] start"
    service:
        name: "hdfs-namenode"
        state: "{{ state }}"
    when: state == "started"

  - name: "[HADOOP][HDFS][SERVICE][NAME] reload"
    service:
        name: "hdfs-namenode"
        state: "{{ state }}"
    when: state == "reloaded"

  - name: "[HADOOP][HDFS][SERVICE][NAME] restart"
    service:
        name: "hdfs-namenode"
        state: "{{ state }}"
    when: state == "restarted"

  - name: "[HADOOP][HDFS][SERVICE][NAME] stop"
    service:
        name: "hdfs-namenode"
        state: "{{ state }}"
    when: state == "stopped"

