---

  - name: apt | cache | update
    apt: update_cache=yes
    when: do_install|bool

  - name: romanesco | deps | install
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - apt-utils
      - autoconf
      - build-essential
      - curl
      - cmake
      - g++
      - gfortran
      - git
      - gzip
      - libbz2-dev
      - libcppunit-dev
      - libexpat-dev
      - libffi-dev
      - libjpeg-dev
      - libpng-dev
      - libsqlite-dev
      - libssl-dev
      - libtool
      - m4
      - make
      - ncurses-dev
      - openjdk-7-jdk
      - openjdk-7-jre-headless
      - openssh-client
      - openssh-server
      - python-pip
      - python-software-properties
      - python2.7-dev
      - rsync
      - sudo
      - tar
      - wget
    when: do_install|bool

  - name: romanesco | service | stop
    service:
        name: romanesco
        state: stopped
    ignore_errors: true
    when: stop_services|bool

  - name: romanesco | install root | delete
    file:
        path: "{{ romanesco_install_root }}"
        state: absent
    when: remove_install_root|bool

  - name: romanesco | data root | delete
    file:
        path: "{{ romanesco_data_root }}"
        state: absent
    when: remove_data_root|bool

  - name: romanesco | install parent | create
    file:
        path: "{{ romanesco_install_parent }}"
        state: directory
    when: do_install|bool

  - name: romanesco | data root | create
    file:
        path: "{{ romanesco_data_root }}"
        state: directory
        mode: 0755
    when: do_install|bool

  - name: romanesco | data root | owner | set
    file:
        path: "{{ romanesco_data_root }}"
        state: directory
        group: "{{ romanesco_group }}"
        owner: "{{ romanesco_user }}"
        mode: 0775
    when: do_install|bool

  - name: romanesco | repo | sync
    command: >
        rsync -avz --exclude=.git
        "{{ romanesco_git_work_dir }}/"
        "{{ romanesco_install_root }}"
    when: do_install|bool

  - name: pip
    pip: requirements={{ romanesco_install_root }}/{{ item }}
    with_items:
      - requirements.txt
      - romanesco/plugins/girder_io/requirements.txt
    when: do_install|bool

  - name: romanesco | script | service | generate
    template:
        src: run-service.j2
        dest: "{{ romanesco_install_root }}/run-service"
        mode: 0755
    when: do_install|bool

  - name: romanesco | conf | owner | set
    file:
        recurse: yes
        path: "{{ romanesco_install_root }}"
        group: "{{ romanesco_group }}"
        mode: 0755
        owner: "{{ romanesco_user }}"
    when: do_install|bool

  - name: romanesco | conf | set
    template:
        src: worker.local.cfg.j2
        dest: "{{ romanesco_install_root }}/romanesco/worker.local.cfg"
        mode: 0644
    when: do_install|bool

