---

dependencies:
  - role: mongodb-variables
  - role: upstart
    name: "{{ mongodb_service }}"
    user: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    description: "MongoDB {{ mongodb_service_description }} Service"
    command: >
      {{ mongodb_install_root }}/bin/{{ mongodb_service_binary }}
      --config {{ mongodb_conf }}/{{ service_subdir }}.conf
    when: do_install|bool
