---

dependencies:
  - role: mesos-variables
  - role: upstart
    name: mesos-slave
    user: "{{ mesos_user }}"
    group: "{{ mesos_group }}"
    description: Mesos Distributed Systems Kernel Slave Service
    command: >
        "{{ mesos_prefix }}/build/bin/mesos-slave.sh"
        "--ip=$( {{ mesos_prefix }}/build/bin/discover-ip.sh )"
        "--master={{ mesos_zookeeper_url }}"
    when: do_install|bool

