---

- hosts: spark
  roles:
    - role: spark-standalone-install
      hadoop_profile: "hadoop2.6"
      ssh_key_exchange_ansible_group: spark

- hosts: head
  roles:
    - role: spark-standalone-service
      spark_slave_ansible_group: spark-slaves
      state: started
