---

dependencies:
  - role: hadoop-variables
  - role: hadoop-hdfs-variables
  - role: hadoop-install
  - role: user-generate
    name: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    crypt_pass: "{{ hdfs_crypt_pass }}"
    system: true
    state: present

