
 - name: "process input arguments"
   set_fact:
       num_yarn_nodes: "{{ yarn_nodes|default(4)|int }}"
       num_hdfs_nodes: "{{ hdfs_nodes|default(4)|int }}"
       num_spark_nodes: "{{ spark_nodes|default(4)|int }}"
       work_dir: "{{ work_dir|default('~/ansible-test-dir') }}"
       docker_dns_ip: "{{ dns_ip|default('172.17.42.1') }}"
       docker_dns_domain: "{{ dns_domain|default('gobig') }}"

 - name: "ensure working directory: {{ work_dir }} exists"
   file:
       path: "{{ work_dir }}"
       state: directory
       mode: 0755

 - name: "resolve working directory to an absolute path"
   shell: readlink -e {{ work_dir }}
   register: abs_work_dir

 - name: "record absolute path"
   set_fact:
       work_dir: "{{ abs_work_dir.stdout }}"

