---

dependencies:
  - role: hadoop-variables
  - role: hadoop-hdfs-variables
  - role: hadoop-install
  - role: hadoop-hdfs-install
  - role: hadoop-hdfs-namenode-service-install
  - role: hadoop-hdfs-namenode-service
