---

  - name: set ec2 pod specification
    set_fact:
        ec2_pod_spec:
            key: gobig
            rules:
              - proto: icmp # ping
                from_port: -1
                to_port: -1
                cidr_ip: 0.0.0.0/0

              - proto: tcp # ssh
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0

              - proto: tcp # mongodb
                from_port: 27017
                to_port: 27017
                cidr_ip: 0.0.0.0/0

              - proto: tcp # mongodb
                from_port: 28017
                to_port: 28017
                cidr_ip: 0.0.0.0/0

              - proto: tcp # hdfs namenode
                from_port: 8020
                to_port: 8020
                cidr_ip: 0.0.0.0/0

              - proto: tcp # hdfs datanode
                from_port: 3888
                to_port: 3888
                cidr_ip: 0.0.0.0/0

              - proto: tcp # hdfs namenode webui
                from_port: 50010
                to_port: 50010
                cidr_ip: 0.0.0.0/0

              - proto: tcp # hdfs datanode webui
                from_port: 50020
                to_port: 50020
                cidr_ip: 0.0.0.0/0

              - proto: tcp # webhdfs
                from_port: 50080
                to_port: 50080
                cidr_ip: 0.0.0.0/0

              - proto: tcp # zookeeper
                from_port: 2181
                to_port: 2181
                cidr_ip: 0.0.0.0/0

              - proto: tcp # mesos master
                from_port: 5050
                to_port: 5050
                cidr_ip: 0.0.0.0/0

              - proto: tcp # mesos slave
                from_port: 5051
                to_port: 5051
                cidr_ip: 0.0.0.0/0

              - proto: tcp # spark dispatcher
                from_port: 7077
                to_port: 7077
                cidr_ip: 0.0.0.0/0

              - proto: tcp
                from_port: 9080 # girder http
                to_port: 9080
                cidr_ip: 0.0.0.0/0

              - proto: tcp
                from_port: 50081 # ???
                to_port: 50081
                cidr_ip: 0.0.0.0/0

              - proto: tcp
                from_port: 8081 # ???
                to_port: 8081
                cidr_ip: 0.0.0.0/0

            hosts:
                0:
                    type: m4.xlarge
                    groups:
                      - datanodes
                      - zookeepers
                      - masters
                      - slaves
                      - spark
                      - uvcmetrics
                      - namenodes
                      - rabbitmq
                      - romanesco
                    volumes:
                        sdb: 50
                        sdc: 50

                1:
                    type: m4.xlarge
                    groups:
                      - datanodes
                      - zookeepers
                      - masters
                      - slaves
                      - spark
                      - uvcmetrics
                      - mongodb
                    volumes:
                        sdb: 50
                        sdc: 50

                2:
                    type: m4.xlarge
                    groups:
                      - datanodes
                      - zookeepers
                      - masters
                      - slaves
                      - spark
                      - uvcmetrics
                      - girder
                    volumes:
                        sdb: 50
                        sdc: 50

