---

  - name: facts | set
    set_fact:
        group: "{{ group|default(name) }}"
        system_group: "{{ (system_group|default(system))|bool }}"

  - name: pkg | whois | install
    apt: name=whois state=present update_cache=yes
    when: state == "present" and crypt_pass == ""

  - name: group | create
    group:
        name: "{{ group }}"
        state: present
        system: "{{ system_group|bool }}"
    when: state == "present"

  - name: user | password | generate
    shell: echo | mkpasswd --method=SHA-512 -s
    register: mkpasswd
    when: state == "present" and crypt_pass == ""

  - name: user | password | record
    set_fact: crypt_pass={{ mkpasswd.stdout }}
    when: state == "present" and crypt_pass == ""

  - name: user | remove
    user:
        name: "{{ name }}"
        state: absent
    when: state == "absent"

  - name: user | create
    user:
        generate_ssh_key: yes
        group: "{{ group }}"
        name: "{{ name }}"
        password: "{{ crypt_pass }}"
        state: present
        system: "{{ system|bool }}"
    when: state == "present"

  - name: user | sshkey | add
    become_user: "{{ name }}"
    authorized_key:
        user: "{{ name }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    when: state == "present"

