---

hdfs_user: hdfs
hdfs_group: hadoop
hdfs_crypt_pass: ""
hdfs_net_interface: eth0

hdfs_data_root: ""
hdfs_block_replication: 3
hdfs_block_size: 268435456 # 256 MiB
hdfs_io_buffer_size: 131072 # 128 KiB

state: started
format: false
